# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: seoyoo <seoyoo@student.42seoul.kr>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/10 15:52:20 by seoyoo            #+#    #+#              #
#    Updated: 2022/07/10 16:51:11 by seoyoo           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# target
NAME = a.out

# compiler
CC = gcc
CFLAGS = -Wall -Wextra -Werror

# rules
all : $(NAME)

$(NAME) :
	$(CC) $(CFLAGS) get_*.c main.c

.PONEY: all
