#ifndef USER_INTERFACE_H
# define USER_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>

// ---------- menu typedef ----------

typedef struct menu
{
    char *str;
    int nth;
    int depth;
    struct menu *next;
    struct menu *prev;
    struct menu *upper;
    struct menu *under;
} menu;

/*
menu array will be generated by a array of strings. In this array, 'menu.str' data should be inside in order and this array should be start with empty string "" and NULL terminated at the end. 

string array should be declared like this following example. 

char *menu_str_arr1[] = {"", "Generate Nodes", "Sort Nodes", "Delete Nodes", "End Program", NULL};
*/

// ---------- prototypes of functions ----------
void print_title(char *title_str);
int get_user_choice(int start, int end);  // returns int what user typed in
menu **menu_node_generator(char **str_arr, menu *upper_category);
int print_menu(menu **menu_arr);
void print_node_arr(menu **node_pointer_arr);
void print_node_info(menu *current);
void menu_node_terminator(menu *menu_node);
void print_all_nodes(menu **highest_menu_arr);
void recursive_print(menu *current);

#endif
